#!/bin/bash

# extract_files.sh - Extract individual files from Full Package export
# 
# Usage: ./extract_files.sh <input_file>
#
# This script extracts individual files from the "Full Package" export
# generated by the editor. The input file should contain multiple files
# separated by comment blocks like:
#
#   /* -----------------------------------------------------------------------
#    * File: filename.ext
#    * ----------------------------------------------------------------------- */
#
# Each file will be extracted to the current directory.

if [ $# -eq 0 ]; then
    echo "Usage: $0 <input_file>"
    echo ""
    echo "Example: $0 full_package.txt"
    echo ""
    echo "This will extract all files from the Full Package export."
    exit 1
fi

INPUT_FILE="$1"

if [ ! -f "$INPUT_FILE" ]; then
    echo "Error: File '$INPUT_FILE' not found!"
    exit 1
fi

echo "Extracting files from $INPUT_FILE..."
echo ""

# Convert Windows line endings to Unix if needed
dos2unix "$INPUT_FILE" 2>/dev/null || sed -i 's/\r$//' "$INPUT_FILE" 2>/dev/null || true

# Use awk to split the file based on the separator pattern
awk '
BEGIN {
    file_count = 0
    current_file = ""
    in_file = 0
}

# Match the file separator pattern
/^\/\* -+$/ {
    # Close previous file if we were writing to one
    if (in_file && current_file != "") {
        close(current_file)
        in_file = 0
    }

    # Read the next line which should contain the filename
    getline
    if ($0 ~ /^ \* File: /) {
        # Extract filename from "* File: filename.ext"
        match($0, /File: (.+)$/, arr)
        current_file = arr[1]
        gsub(/^[ \t]+|[ \t]+$/, "", current_file)  # Trim whitespace

        # Skip the closing separator line
        getline

        in_file = 1
        file_count++
        printf "Extracting: %s\n", current_file
        next
    }
}

# Write content to current file (skip empty lines at the start)
in_file {
    print $0 >> current_file
}

END {
    if (in_file && current_file != "") {
        close(current_file)
    }
    printf "\nExtraction complete!\n"
    printf "Total files extracted: %d\n", file_count
}
' "$INPUT_FILE"

echo ""
echo "Done! Files extracted to current directory."

